#### Numpy
Numpy is a fundamental library fro scientific computing in Python.It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.
Sammary:
1. Create a 1D array
2. 1D array's reshape
3. Create a 2D array: Customize,arange,ones,eye,zeros
4. Attributes of Numpy Array:shape,ndim, size, dtype, itemsize
5. Numpy Vectorized operation:+, -, *, /
6. Universal Function:sqrt, exp, sin, log, mean, median, std, var
7. Array slicing and Indexing
8.Two applications of Numpy: statistical concepts--Normalization, logical operation

In [4]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
## 1d array's reshape
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [10]:
## 2d array
arr2 = np.array([[1,2,3,4,5]])
print(arr2.shape)

(1, 5)


In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
## Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size(number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(number of elements): 6
Data type: int64
Item size (in bytes): 8


In [25]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element wise addition
print("Addition:", arr1+arr2)

### Element wise substraction
print("Substraction:", arr1-arr2)

### Element wise multiplication
print("Multiplication:", arr1 * arr2)

### Element wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [52]:
## Universal Function
arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sin
print(np.sin(arr))

## natural log
print(np.log(arr))

## Mean
print(np.mean(arr))

## Median
print(np.median(arr))

## standard deviation
print(np.std(arr))

## Variance
print(np.var(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
4.0
4.0
1.4142135623730951
2.0


In [30]:
## array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
print(arr[0][0])
print(arr[0:2][0])
print(arr[0:2, 0:2])

1
[1 2 3 4]
[[1 2]
 [5 6]]


In [42]:
## Modify array elements
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [44]:
arr[1:, 1:]=100
print(arr)

[[100   2   3   4]
 [  5 100 100 100]
 [  9 100 100 100]]


#### Two Application

In [47]:
### statistical concepts--Nomalization
###to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
## logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data > 5
data[(data > 5) & (data <= 8)]

array([6, 7, 8])