# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [6]:
import numpy as np

# Create a Numpy array of shape (5,5) filled with random integers
array=np.random.randint(1,21,size=(5,5))
print("Original array:", array)

# Replace all the elements in the third column with 1
array[:,2] = 1
print("Modified array:", array)




Original array: [[14 13  3  8 19]
 [10 13  5  2  5]
 [ 6  4 15 14 15]
 [16  7  9  7  3]
 [15 16  9  8  7]]
Modified array: [[14 13  1  8 19]
 [10 13  1  2  5]
 [ 6  4  1 14 15]
 [16  7  1  7  3]
 [15 16  1  8  7]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [14]:
# Create a Numpy array of shape (4,4) with values from 1 to 16
array=np.arange(1,17).reshape(4,4)
print("Original array:\n", array)

# Replace the diagonal element with 0
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [19]:
# Create a Numpy array of shape (6,6) with values from 1 to 36
array=np.arange(1,37).reshape(6,6)
print("Original_array:\n", array)

# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns
sub_array=array[2:5, 1:4]
print("Sub_array:\n", sub_array)

Original_array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub_array:
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [ ]:
# Create a NumPy array of shape (5, 5) with random integers
array=np.random.randint(1, 21, size=(5,5))
print("Original array:\n", array)

# Extract the elements on the border
border_elements=np.concatenate((array[0,:],array[-1,:],array[:,0],array[:,-1]))
print("Border elements:\n", border_elements)

Original array:
 [[18 14  3  3  7]
 [10  5 16  3 11]
 [ 5 12  9  5  1]
 [10  6 15 20 16]
 [ 1  2  6  6 19]]
Border elements:
 [18 14  3  3  7  1  2  6  6 19 18 10  5 10  1  7 11  1 16 19]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [33]:
array1=np.random.randint(1,21,size=(3,4))
array2=np.random.randint(1,21,size=(3,4))

print("Array1:\n", array1)
print("Array2:\n", array2)

array_wise=array1 + array2
print("array_wise:\n", array_wise)

array_sub=array1 - array2
print("array_sub:\n", array_sub)

array_mul=array1 * array2
print("array_mul:\n", array_mul)

array_div=array1 / array2
print("array_div:\n", array_div)


Array1:
 [[12 12 16  1]
 [ 7 19 16  1]
 [19 19 14 16]]
Array2:
 [[14  7 18 10]
 [ 4 14  2 12]
 [15 14 16 20]]
array_wise:
 [[26 19 34 11]
 [11 33 18 13]
 [34 33 30 36]]
array_sub:
 [[ -2   5  -2  -9]
 [  3   5  14 -11]
 [  4   5  -2  -4]]
array_mul:
 [[168  84 288  10]
 [ 28 266  32  12]
 [285 266 224 320]]
array_div:
 [[0.85714286 1.71428571 0.88888889 0.1       ]
 [1.75       1.35714286 8.         0.08333333]
 [1.26666667 1.35714286 0.875      0.8       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [37]:
array=np.arange(1,17).reshape(4,4)
print("array:\n", array)

row_sum=np.sum(array,axis=1)
column_sum=np.sum(array,axis=0)
print("Row-wise sum:\n", row_sum)
print("Column-wise sum:\n",column_sum)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
 [10 26 42 58]
Column-wise sum:
 [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [39]:
array=np.random.randint(1,21,size=(5,5))
print("Array:\n",array)

mean=np.mean(array)
print("Mean:\n",mean)

median=np.median(array)
print("Median:\n",median)

std=np.std(array)
print("Standard Deviation:\n",std)

var=np.var(array)
print("Variance:\n",var)

Array:
 [[ 8 15  8 15 10]
 [11 18  2 11 18]
 [13 14 17 16  9]
 [ 2 10 17  5  6]
 [14 15 10  4  9]]
Mean:
 11.08
Median:
 11.0
Standard Deviation:
 4.757478323650041
Variance:
 22.6336


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [42]:
array=np.arange(1,10).reshape(3,3)
print("Array:\n", array)

mean=np.mean(array)
std=np.std(array)

normalized_array=(array-mean)/std
print("Normalized array:\n", normalized_array)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [ ]:
array=np.random.randint(1,21,size=(3,3))
row_array=np.random.randint(1,21,size=(3,))
print("Original array:\n", array)
print("Row array:\n", row_array)

# 利用广播机制对二维数组逐行加上一维数组
result = array + row_array
print("Result:\n", result)

Original array:
 [[15 14  1]
 [15  2 15]
 [ 2 14  2]]
Row array:
 [1 1 1]
Result:
 [[16 15  2]
 [16  3 16]
 [ 3 15  3]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [47]:
array=np.random.randint(1,21,size=(4,4))
column_array=np.random.randint(1,21,size=(4,))
print("Original array:\n", array)
print("Row array:\n", column_array)

print("Column array:\n", column_array[:, np.newaxis])
# 利用广播机制对二维数组逐列减去一维数组
result = array - column_array[:, np.newaxis]
print("Result:\n", result)


Original array:
 [[12  2 16 10]
 [ 2  3  2 13]
 [11 15  4 20]
 [10 19 19  6]]
Row array:
 [12  8 18  6]
Column array:
 [[12]
 [ 8]
 [18]
 [ 6]]
Result:
 [[  0 -10   4  -2]
 [ -6  -5  -6   5]
 [ -7  -3 -14   2]
 [  4  13  13   0]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [64]:
matrix=np.random.randint(1,21,size=(3,3))
print("Matrix:\n", matrix)

# Compute the determinant
determinant=np.linalg.det(matrix)
print("Determinant:\n", determinant)

# Compute the inverse
inverse=np.linalg.inv(matrix)
print("Inverse:\n", inverse)

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors=np.linalg.eig(matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Matrix:
 [[10 18 17]
 [ 4  9  4]
 [18 12 18]]
Determinant:
 -797.9999999999995
Inverse:
 [[-1.42857143e-01  1.50375940e-01  1.01503759e-01]
 [-1.95921710e-17  1.57894737e-01 -3.50877193e-02]
 [ 1.42857143e-01 -2.55639098e-01 -2.25563910e-02]]
Eigenvalues:
 [36.22630268 -4.32248731  5.09618463]
Eigenvectors:
 [[-0.62677313 -0.79148271 -0.07839721]
 [-0.20262301  0.05487244 -0.67313844]
 [-0.75239574  0.60872336  0.73534925]]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [67]:
matrix1=np.random.randint(1,11,size=(2,3))
matrix2=np.random.randint(1,11,size=(3,2))
print("Matrix1:\n", matrix1)
print("Matrix2:\n", matrix2)

# Matrix multiplication
result=np.dot(matrix1, matrix2)
print("Matrix multiplication result:\n", result)

Matrix1:
 [[8 6 2]
 [5 1 5]]
Matrix2:
 [[ 3  5]
 [ 9 10]
 [ 7  5]]
Matrix multiplication result:
 [[ 92 110]
 [ 59  60]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [68]:
array1=np.arange(1,10).reshape(3,3)
print("Original array(3,3):\n", array1)

array2=array1.reshape(1,9)
print("Reshaped array(1,9):\n", array2)

array3=array1.reshape(9,1)
print("Reshaped array(9,1):\n", array3)

Original array(3,3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array(1,9):
 [[1 2 3 4 5 6 7 8 9]]
Reshaped array(9,1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [69]:
array1=np.random.randint(1,11,size=(5,5))
print("Original array:\n", array1)

flattened_array=array1.flatten()
print("Flattened array:\n", flattened_array)

reshaped_array=flattened_array.reshape(5,5)
print("Reshaped array:\n", reshaped_array)


Original array:
 [[ 8 10  5  4  4]
 [ 9  1  7  8  3]
 [ 3  5  4  5  1]
 [ 3 10  8  8 10]
 [ 1 10  6  1  4]]
Flattened array:
 [ 8 10  5  4  4  9  1  7  8  3  3  5  4  5  1  3 10  8  8 10  1 10  6  1
  4]
Reshaped array:
 [[ 8 10  5  4  4]
 [ 9  1  7  8  3]
 [ 3  5  4  5  1]
 [ 3 10  8  8 10]
 [ 1 10  6  1  4]]


### Assignment 8: Fancy Indexing（花式索引）and Boolean Indexing（布尔索引）

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [71]:
array=np.random.randint(1,11,size=(5,5))
print("Original array:\n", array)

corners=array[[0,0,-1,-1],[0,-1,0,-1]]
print("Corners:\n", corners)


Original array:
 [[ 8  8  4  9  3]
 [ 4  8  2 10  4]
 [ 9  2  5  9  9]
 [ 3  3  2  8 10]
 [ 4  5  2  7  3]]
Corners:
 [8 3 4 3]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [74]:
array=np.random.randint(1,21,size=(4,4))
array[array>10] = 10
print("Modified array:\n", array)

Modified array:
 [[ 6  7 10  9]
 [10  3 10 10]
 [ 6 10 10 10]
 [ 7 10  3  5]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [79]:
# Create a structured array with fields 'name' and 'age' and 'weight'
data_type = [('name','U10'), ('age','i4'), ('weigth','f4')]
data = np.array([('Alice',25,55.5), ('Bob',30,70.0), ('Charlie',35,80.0)], dtype=data_type)
print("Original array:\n", data)

# Sort the array by 'age'
sorted_data = np.sort(data, order='age')
print("Sorted array:\n", sorted_data)

Original array:
 [('Alice', 25, 55.5) ('Bob', 30, 70. ) ('Charlie', 35, 80. )]
Sorted array:
 [('Alice', 25, 55.5) ('Bob', 30, 70. ) ('Charlie', 35, 80. )]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [80]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)], dtype=data_type)
print("Original array:\n", data)

# Compute the Euclidean distance between each pair of points
## NumPy会自动广播，生成一个n×n的矩阵，其中每个元素(i,j)表示第i个点与第j个点的x坐标差值
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:\n", distances)


Original array:
 [(1, 2) (3, 4) (5, 6)]
Euclidean distances:
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays(掩码数组)

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [83]:
import numpy.ma as ma
# Create a masked array of shape(4,4) with random integers
array=np.random.randint(1,21,size=(4,4))
masked_array=ma.masked_array(array, mask=array>10)
print("Original array:\n", array)
print("Masked array:\n", masked_array)

# Compute the sum of the unmasked elements
sum_unmasked=ma.sum(masked_array)
print("Sum of unmasked elements:\n", sum_unmasked)

Original array:
 [[11 14 12 16]
 [12 12 14  2]
 [ 9 14 10 19]
 [ 7 16  6  7]]
Masked array:
 [[-- -- -- --]
 [-- -- -- 2]
 [9 -- 10 --]
 [7 -- 6 7]]
Sum of unmasked elements:
 41


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [86]:
# Create a masked array of shape(3,3) with random integers
array=np.random.randint(1,21,size=(3,3))
masked_array=ma.masked_array(array, mask=np.eye(3,dtype=bool))
print("Original array:\n", array)
print("Masked array:\n", masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked=ma.mean(masked_array)
masked_array=ma.filled(masked_array, mean_unmasked)
print("Masked array with mean filled:\n", masked_array)

Original array:
 [[ 2  3  4]
 [18 15 20]
 [ 5 12 14]]
Masked array:
 [[-- 3 4]
 [18 -- 20]
 [5 12 --]]
Masked array with mean filled:
 [[10  3  4]
 [18 10 20]
 [ 5 12 10]]
